django-pygit2:
    image: alpine:edge
    container_name: "django-pygit2"
    ports:
      - "8000:8000"
    volumes:
      - "../:/app"
    working_dir: /app
    entrypoint: "/bin/sh -c \"while true; do echo hello world; sleep 1; done\""
