# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20160102_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(default=b'master', help_text=b'Source branch to pull from (default is master)', max_length=255),
        ),
    ]
